[server]
enableCORS = false
maxUploadSize = 500

[dev]
base_url = "http://10.97.59.123:8000/v1/"
embedding = "intfloat/multilingual-e5-large-instruct"
chat = "google/gemma-3-1b-it"

[openai]
base_url= "https://api.openai.com/v1"
embedding = "text-embedding-3-large"
chat = "gpt-4o"

[OpenRouter]
base_url= "https://openrouter.ai/api/v1"
embedding = "text-embedding-3-large"
chat = "google/gemma-3-27b-it:free"


